// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as YasminaaiApi from "../../../index.js";

export declare namespace OtPsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class OtPsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<OtPsClient.Options>;

    constructor(options: OtPsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * This endpoint sends a one-time password (OTP) to the provided email and phone number for quote verification. It should be called before creating a quote request.
     *
     * @param {YasminaaiApi.PostQuoteOtpRequest} request
     * @param {OtPsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link YasminaaiApi.BadRequestError}
     * @throws {@link YasminaaiApi.UnauthorizedError}
     *
     * @example
     *     await client.otPs.requestOtpForQuoteVerification({
     *         email: "someone@example.com",
     *         phone: "0501234567",
     *         owner_id: "1012345678"
     *     })
     */
    public requestOtpForQuoteVerification(
        request: YasminaaiApi.PostQuoteOtpRequest,
        requestOptions?: OtPsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__requestOtpForQuoteVerification(request, requestOptions));
    }

    private async __requestOtpForQuoteVerification(
        request: YasminaaiApi.PostQuoteOtpRequest,
        requestOptions?: OtPsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.YasminaaiApiEnvironment.Sandbox,
                "quote-otp",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new YasminaaiApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new YasminaaiApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.YasminaaiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/quote-otp");
    }

    /**
     * This endpoint sends a one-time password (OTP). It should be called before issuing a policy.
     *
     * @param {YasminaaiApi.PostIssueOtpRequest} request
     * @param {OtPsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link YasminaaiApi.BadRequestError}
     * @throws {@link YasminaaiApi.UnauthorizedError}
     *
     * @example
     *     await client.otPs.requestOtpForIssuingPolicy({
     *         email: "someone@example.com",
     *         phone: "0501234567",
     *         owner_id: "1012345678",
     *         quote_request_id: 123,
     *         quote_reference_id: "550e8400-e29b-41d4-a716-446655440000",
     *         quote_price_id: "550e8400-e29b-41d4-a716-446655440001"
     *     })
     */
    public requestOtpForIssuingPolicy(
        request: YasminaaiApi.PostIssueOtpRequest,
        requestOptions?: OtPsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__requestOtpForIssuingPolicy(request, requestOptions));
    }

    private async __requestOtpForIssuingPolicy(
        request: YasminaaiApi.PostIssueOtpRequest,
        requestOptions?: OtPsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.YasminaaiApiEnvironment.Sandbox,
                "issue-otp",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new YasminaaiApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new YasminaaiApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.YasminaaiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/issue-otp");
    }
}
