// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetPoliciesRequest {
    quote_request_id?: number;
    quote_price_id?: string;
    provider_policy_id?: number;
    car_sequence_number?: string;
    new_owner_id?: string;
    previous_owner_id?: string;
    status?: number;
    min_price?: number;
    max_price?: number;
    per_page?: number;
}
