// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         carPolicy: 1
 *     }
 */
export interface GetPoliciesCarPolicyRequest {
    carPolicy: number;
}
