// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         quote_request_id: 123,
 *         quote_reference_id: "550e8400-e29b-41d4-a716-446655440000",
 *         quote_price_id: "550e8400-e29b-41d4-a716-446655440001"
 *     }
 */
export interface PostPoliciesRequest {
    /** ID of the car quote request */
    quote_request_id: number;
    /** Unique identifier for the quote reference ID (coming from POST /quote-requests) */
    quote_reference_id: string;
    /** Unique identifier for the quote price ID that exists inside a quote item (coming from POST /quote-requests) */
    quote_price_id: string;
    /** List of benefit UUIDs */
    benefits?: string[];
    /** Optional free-form object with additional fields. Total JSON-encoded size must not exceed 255 characters. */
    extra_fields?: Record<string, unknown>;
}
