// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         date_from: "2026-06-01",
 *         date_to: "2026-06-30",
 *         per_page: 10,
 *         include_aggregates: true
 *     }
 */
export interface GetQuoteRequestsRequest {
    /** Inclusive lower bound for quote request creation date. */
    date_from?: string;
    /** Inclusive upper bound for quote request creation date. */
    date_to?: string;
    /** Number of quote requests to return per page. */
    per_page?: number;
    /** When true, includes quote request totals and monthly buckets for the filtered result set. */
    include_aggregates?: boolean;
}
