// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         owner_id: "owner_id",
 *         phone: "phone",
 *         birthdate: "2023-01-15",
 *         car_sequence_number: "car_sequence_number",
 *         car_estimated_cost: 1.1
 *     }
 */
export interface PostQuoteRequestsRequest {
    /** Owner ID must be 10 digits starting with 1, 2, or 7 */
    owner_id: string;
    /** Email address must be valid and belongs to the customer */
    email?: string;
    /** Phone number must start with 05 and be 10 digits */
    phone: string;
    /** Birthdate in YYYY-MM-DD format */
    birthdate: string;
    /** Car sequence number must be 8 or 9 digits */
    car_sequence_number: string;
    /** Indicates if the ownership is being transferred */
    is_ownership_transfer?: boolean;
    /** Required if is_ownership_transfer is true; 10 digits starting with 1,2,7 */
    current_car_owner_id?: string;
    /** Estimated cost of the car */
    car_estimated_cost: number;
    /** Car model year between 1950 and next year */
    car_model_year?: number;
    /** Desired policy start date in YYYY-MM-DD. Must be between tomorrow and 28 days from today (inclusive). The platform validates this range server-side. */
    start_date?: string;
    /** List of drivers for the vehicle. When provided, the sum of all driving_percentage values must equal 100, and the owner must be included among the drivers. */
    drivers?: PostQuoteRequestsRequest.Drivers.Item[];
}

export namespace PostQuoteRequestsRequest {
    export type Drivers = Drivers.Item[];

    export namespace Drivers {
        export interface Item {
            /** Driver's national ID. Must be 10 digits starting with 1, 2, or 7. */
            owner_id: string;
            /** Driver's birthdate in YYYY-MM-DD format. */
            birthdate: string;
            /** Percentage of driving for this driver. Valid values are 25, 50, 75, or 100. The sum of all drivers' percentages must equal 100. */
            driving_percentage: number;
        }
    }
}
