// This file was auto-generated by Fern from our API Definition.

export interface Benefit {
    quote_benefit_id?: string | undefined;
    id?: string | undefined;
    name?: string | undefined;
    amount?: number | undefined;
    vat?: number | undefined;
    url?: (string | null) | undefined;
}
