// This file was auto-generated by Fern from our API Definition.

import type * as YasminaaiApi from "../index.js";

export interface CompanyQuote {
    company_name?: string | undefined;
    prices?: YasminaaiApi.QuotePrice[] | undefined;
    benefits?: YasminaaiApi.Benefit[] | undefined;
}
