// This file was auto-generated by Fern from our API Definition.

import type * as YasminaaiApi from "../index.js";

export interface PaginatedPolicyResponse {
    current_page?: number | undefined;
    data?: YasminaaiApi.Policy[] | undefined;
    first_page_url?: string | undefined;
    from?: (number | null) | undefined;
    last_page?: number | undefined;
    last_page_url?: string | undefined;
    links?: YasminaaiApi.PaginationLink[] | undefined;
    next_page_url?: (string | null) | undefined;
    path?: string | undefined;
    per_page?: number | undefined;
    prev_page_url?: (string | null) | undefined;
    to?: (number | null) | undefined;
    total?: number | undefined;
    aggregates?: YasminaaiApi.PolicyAggregates | undefined;
}
