// This file was auto-generated by Fern from our API Definition.

import type * as YasminaaiApi from "../index.js";

/**
 * Returned only when include_aggregates is true.
 */
export interface PolicyAggregates {
    total_count?: number | undefined;
    total_price?: number | undefined;
    /** Monthly policy counts and sales totals keyed by YYYY-MM. For issued policies (`status=1`), buckets use `uploaded_at` and fall back to `created_at`. */
    by_month?: Record<string, YasminaaiApi.PolicyMonthAggregate> | undefined;
}
