// This file was auto-generated by Fern from our API Definition.

export interface Policy {
    id?: number | undefined;
    meta_data?: Record<string, unknown> | undefined;
    start_date?: string | undefined;
    provider_policy_id?: number | undefined;
    provider_policy?: string | undefined;
    order_status?: number | undefined;
    approval_status?: number | undefined;
    end_date?: string | undefined;
    is_claimed?: boolean | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    client_id?: string | undefined;
    canceled_at?: (string | null) | undefined;
    invoice?: string | undefined;
    cancellation_document?: string | undefined;
}
