// This file was auto-generated by Fern from our API Definition.

export interface QuotePrice {
    quote_price_id?: string | undefined;
    deductible?: number | undefined;
    subtotal?: number | undefined;
    vat_percentage?: number | undefined;
    vat?: number | undefined;
    total?: number | undefined;
}
