// This file was auto-generated by Fern from our API Definition.

/**
 * Returned only when include_aggregates is true.
 */
export interface QuoteRequestAggregates {
    total_count?: number | undefined;
    /** Monthly quote request counts keyed by YYYY-MM. */
    by_month?: Record<string, number> | undefined;
}
