// This file was auto-generated by Fern from our API Definition.

import type * as YasminaaiApi from "../index.js";

export interface QuoteResponse {
    /** The owner’s national ID or Iqama ID */
    owner_id?: number | undefined;
    /** The owner's phone number */
    phone?: string | undefined;
    /** The owner's birthdate. Hijri for Saudi nationals, Gregorian for others */
    birthdate?: string | undefined;
    /** The car sequence number from 9 digits */
    car_sequence_number?: number | undefined;
    /** Whether it was a car transfer or not */
    is_ownership_transfer?: boolean | undefined;
    /** The estimated cost of the car */
    car_estimated_cost?: number | undefined;
    /** The car model year */
    car_model_year?: number | undefined;
    /** Requested policy start date in YYYY-MM-DD. Returned if provided in the quote request. */
    start_date?: string | undefined;
    /** List of drivers associated with this quote request. Returned if drivers were provided in the request. */
    drivers?: QuoteResponse.Drivers.Item[] | undefined;
    /** An array representing each insurance company quote. Each item has the company name, the prices, and the benefits. */
    quotes?: QuoteResponse.Quotes.Item[] | undefined;
    /** Your own client ID */
    client_id?: string | undefined;
    /** In case of an update on this quote, this date will change */
    updated_at?: string | undefined;
    /** When was the quote requested */
    created_at?: string | undefined;
    /** Yasmina ID for the quote. You can use it to delete items or showing it again to the customer */
    id?: number | undefined;
}

export namespace QuoteResponse {
    export type Drivers = Drivers.Item[];

    export namespace Drivers {
        export interface Item {
            /** Driver's national ID (10 digits starting with 1, 2, or 7) */
            owner_id?: string | undefined;
            /** Driver's birthdate in YYYY-MM-DD format */
            birthdate?: string | undefined;
            /** Percentage of driving for this driver (25, 50, 75, or 100) */
            driving_percentage?: number | undefined;
        }
    }

    export type Quotes = Quotes.Item[];

    export namespace Quotes {
        export interface Item {
            company_name?: string | undefined;
            /** An array representing each price. This will have the premium and the deductible */
            prices?: YasminaaiApi.QuotePrice[] | undefined;
            /** An array representing the different benefits offered by the company. Some of them are free and comes with the insurance, some are paid and optional */
            benefits?: YasminaaiApi.Benefit[] | undefined;
        }
    }
}
