// This file was auto-generated by Fern from our API Definition.

import type * as YasminaaiApi from "../index.js";

export interface QuoteResponse {
    /** The owner’s national ID or Iqama ID */
    owner_id?: number | undefined;
    /** The owner's phone number */
    phone?: string | undefined;
    /** The owner's birthdate. Hijri for Saudi nationals, Gregorian for others */
    birthdate?: string | undefined;
    /** The car sequence number from 9 digits */
    car_sequence_number?: number | undefined;
    /** Custom car number for newly imported cars (present when `custom_number` was used in the request) */
    custom_number?: string | undefined;
    /** Whether it was a car transfer or not */
    is_ownership_transfer?: boolean | undefined;
    /** The estimated cost of the car */
    car_estimated_cost?: number | undefined;
    /** The car model year */
    car_model_year?: number | undefined;
    /** Requested policy start date in YYYY-MM-DD. Returned if provided in the quote request. */
    start_date?: string | undefined;
    /** List of drivers associated with this quote request. Returned if drivers were provided in the request. */
    drivers?: QuoteResponse.Drivers.Item[] | undefined;
    /** An array representing each insurance company quote. Each item has the company name, the prices, and the benefits. */
    quotes?: QuoteResponse.Quotes.Item[] | undefined;
    /** Your own client ID */
    client_id?: string | undefined;
    /** In case of an update on this quote, this date will change */
    updated_at?: string | undefined;
    /** When was the quote requested */
    created_at?: string | undefined;
    /** Yasmina ID for the quote. You can use it to delete items or showing it again to the customer */
    id?: number | undefined;
}

export namespace QuoteResponse {
    export type Drivers = Drivers.Item[];

    export namespace Drivers {
        export interface Item {
            /** Driver's national ID (10 digits starting with 1, 2, or 7) */
            owner_id?: string | undefined;
            /** Driver's birthdate in YYYY-MM-DD format */
            birthdate?: string | undefined;
            /** Percentage of driving for this driver (25, 50, 75, or 100) */
            driving_percentage?: number | undefined;
        }
    }

    export type Quotes = Quotes.Item[];

    export namespace Quotes {
        export interface Item {
            company_name?: string | undefined;
            /** Arabic name of the insurance company. Use this field instead of `company_name` when rendering Arabic UIs. */
            company_name_ar?: string | undefined;
            /** Normalised insurance category used to group and filter quotes. Always one of `TPL`, `TPL +`, or `Comprehensive`. */
            type?: Item.Type | undefined;
            /** The insurance type label exactly as the insurance provider intends it to be displayed. While `type` normalises all non-TPL / non-Comprehensive values into `TPL +`, this field preserves the original provider string (e.g. "TPL Plus", "Third Party Plus") and should be shown in the UI wherever the provider's own wording is preferred. */
            insurance_type_display?: string | undefined;
            /** Arabic translation of `insurance_type_display`. Use this field for Arabic UIs. Falls back to the English value for provider-specific types that do not have a translation. */
            insurance_type_display_ar?: string | undefined;
            /** CDN URL for the insurance company's logo. */
            company_logo_url?: string | undefined;
            /** CDN URL for the insurance company's square logo. */
            square_company_logo_url?: string | undefined;
            /** An array representing each price. This will have the premium and the deductible */
            prices?: YasminaaiApi.QuotePrice[] | undefined;
            /** An array representing the different benefits offered by the company. Some of them are free and comes with the insurance, some are paid and optional */
            benefits?: YasminaaiApi.Benefit[] | undefined;
        }

        export namespace Item {
            /** Normalised insurance category used to group and filter quotes. Always one of `TPL`, `TPL +`, or `Comprehensive`. */
            export const Type = {
                Tpl: "TPL",
                Comprehensive: "Comprehensive",
            } as const;
            export type Type = (typeof Type)[keyof typeof Type];
        }
    }
}
