// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         email: "someone@example.com",
 *         phone: "0501234567",
 *         owner_id: "1012345678"
 *     }
 */
export interface PostQuoteOtpRequest {
    /** Email address of the car owner */
    email: string;
    /** Phone number starting with 05 and containing 10 digits */
    phone: string;
    /** National ID or Iqama ID of the car owner (10 digits) */
    owner_id: string;
}
