// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         email: "someone@example.com",
 *         phone: "0501234567",
 *         owner_id: "1012345678",
 *         quote_request_id: 123,
 *         quote_reference_id: "550e8400-e29b-41d4-a716-446655440000",
 *         quote_price_id: "550e8400-e29b-41d4-a716-446655440001"
 *     }
 */
export interface PostIssueOtpRequest {
    /** Email address of the car owner */
    email: string;
    /** Phone number starting with 05 and containing 10 digits */
    phone: string;
    /** National ID or Iqama ID of the car owner (10 digits) */
    owner_id: string;
    /** ID of the car quote request */
    quote_request_id: number;
    /** Unique identifier for the quote reference ID (coming from POST /quote-requests) */
    quote_reference_id: string;
    /** Unique identifier for the quote price ID that exists inside a quote item (coming from POST /quote-requests) */
    quote_price_id: string;
}
