// This file was auto-generated by Fern from our API Definition.

import type * as YasminaaiApi from "../../../index.js";

export interface GetQuoteRequestsResponse {
    current_page?: number | undefined;
    data?: YasminaaiApi.QuoteResponse[] | undefined;
    first_page_url?: string | undefined;
    from?: (number | null) | undefined;
    last_page?: number | undefined;
    last_page_url?: string | undefined;
    links?: GetQuoteRequestsResponse.Links.Item[] | undefined;
    next_page_url?: string | undefined;
    path?: string | undefined;
    per_page?: number | undefined;
    prev_page_url?: string | undefined;
    to?: (number | null) | undefined;
    total?: number | undefined;
}

export namespace GetQuoteRequestsResponse {
    export type Links = Links.Item[];

    export namespace Links {
        export interface Item {
            url?: string | undefined;
            label?: string | undefined;
            active?: boolean | undefined;
        }
    }
}
