// This file was auto-generated by Fern from our API Definition.

export const PostQuoteRequestsRequestAcceptLanguage = {
    Ar: "ar",
} as const;
export type PostQuoteRequestsRequestAcceptLanguage =
    (typeof PostQuoteRequestsRequestAcceptLanguage)[keyof typeof PostQuoteRequestsRequestAcceptLanguage];
