// This file was auto-generated by Fern from our API Definition.

import * as YasminaaiApi from "../../src/api/index";
import { YasminaaiApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("OtPsClient", () => {
    test("requestOtpForQuoteVerification (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new YasminaaiApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { email: "someone@example.com", phone: "0501234567", owner_id: "1012345678" };

        server.mockEndpoint().post("/quote-otp").jsonBody(rawRequestBody).respondWith().statusCode(200).build();

        const response = await client.otPs.requestOtpForQuoteVerification({
            email: "someone@example.com",
            phone: "0501234567",
            owner_id: "1012345678",
        });
        expect(response).toEqual(undefined);
    });

    test("requestOtpForQuoteVerification (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new YasminaaiApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { email: "email", phone: "phone", owner_id: "owner_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/quote-otp")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.otPs.requestOtpForQuoteVerification({
                email: "email",
                phone: "phone",
                owner_id: "owner_id",
            });
        }).rejects.toThrow(YasminaaiApi.BadRequestError);
    });

    test("requestOtpForQuoteVerification (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new YasminaaiApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { email: "email", phone: "phone", owner_id: "owner_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/quote-otp")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.otPs.requestOtpForQuoteVerification({
                email: "email",
                phone: "phone",
                owner_id: "owner_id",
            });
        }).rejects.toThrow(YasminaaiApi.UnauthorizedError);
    });

    test("requestOtpForIssuingPolicy (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new YasminaaiApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            email: "someone@example.com",
            phone: "0501234567",
            owner_id: "1012345678",
            quote_request_id: 123,
            quote_reference_id: "550e8400-e29b-41d4-a716-446655440000",
            quote_price_id: "550e8400-e29b-41d4-a716-446655440001",
        };

        server.mockEndpoint().post("/issue-otp").jsonBody(rawRequestBody).respondWith().statusCode(200).build();

        const response = await client.otPs.requestOtpForIssuingPolicy({
            email: "someone@example.com",
            phone: "0501234567",
            owner_id: "1012345678",
            quote_request_id: 123,
            quote_reference_id: "550e8400-e29b-41d4-a716-446655440000",
            quote_price_id: "550e8400-e29b-41d4-a716-446655440001",
        });
        expect(response).toEqual(undefined);
    });

    test("requestOtpForIssuingPolicy (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new YasminaaiApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            email: "email",
            phone: "phone",
            owner_id: "owner_id",
            quote_request_id: 1,
            quote_reference_id: "quote_reference_id",
            quote_price_id: "quote_price_id",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/issue-otp")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.otPs.requestOtpForIssuingPolicy({
                email: "email",
                phone: "phone",
                owner_id: "owner_id",
                quote_request_id: 1,
                quote_reference_id: "quote_reference_id",
                quote_price_id: "quote_price_id",
            });
        }).rejects.toThrow(YasminaaiApi.BadRequestError);
    });

    test("requestOtpForIssuingPolicy (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new YasminaaiApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            email: "email",
            phone: "phone",
            owner_id: "owner_id",
            quote_request_id: 1,
            quote_reference_id: "quote_reference_id",
            quote_price_id: "quote_price_id",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/issue-otp")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.otPs.requestOtpForIssuingPolicy({
                email: "email",
                phone: "phone",
                owner_id: "owner_id",
                quote_request_id: 1,
                quote_reference_id: "quote_reference_id",
                quote_price_id: "quote_price_id",
            });
        }).rejects.toThrow(YasminaaiApi.UnauthorizedError);
    });
});
