// This file was auto-generated by Fern from our API Definition.

import * as YasminaaiApi from "../../src/api/index";
import { YasminaaiApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PoliciesClient", () => {
    test("showPolicy", async () => {
        const server = mockServerPool.createServer();
        const client = new YasminaaiApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: 1,
            meta_data: { key: "value" },
            start_date: "start_date",
            provider_policy_id: 1,
            provider_policy: "provider_policy",
            order_status: 1,
            approval_status: 1,
            end_date: "end_date",
            is_claimed: true,
            created_at: "created_at",
            updated_at: "updated_at",
            client_id: "client_id",
            canceled_at: "canceled_at",
            invoice: "invoice",
            cancellation_document: "cancellation_document",
        };

        server.mockEndpoint().get("/policies/1").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.policies.showPolicy({
            carPolicy: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listPolicies (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new YasminaaiApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                id: 1,
                meta_data: { key: "value" },
                start_date: "start_date",
                provider_policy_id: 1,
                provider_policy: "provider_policy",
                order_status: 1,
                approval_status: 1,
                end_date: "end_date",
                is_claimed: true,
                created_at: "created_at",
                updated_at: "updated_at",
                client_id: "client_id",
                canceled_at: "canceled_at",
                invoice: "invoice",
                cancellation_document: "cancellation_document",
            },
        ];

        server.mockEndpoint().get("/policies").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.policies.listPolicies();
        expect(response).toEqual(rawResponseBody);
    });

    test("listPolicies (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new YasminaaiApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/policies").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.policies.listPolicies();
        }).rejects.toThrow(YasminaaiApi.UnauthorizedError);
    });

    test("issuePolicy (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new YasminaaiApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            quote_request_id: 123,
            quote_reference_id: "550e8400-e29b-41d4-a716-446655440000",
            quote_price_id: "550e8400-e29b-41d4-a716-446655440001",
        };
        const rawResponseBody = {
            id: 1,
            meta_data: { key: "value" },
            start_date: "start_date",
            provider_policy_id: 1,
            provider_policy: "provider_policy",
            order_status: 1,
            approval_status: 1,
            end_date: "end_date",
            is_claimed: true,
            created_at: "created_at",
            updated_at: "updated_at",
            client_id: "client_id",
            canceled_at: "canceled_at",
            invoice: "invoice",
            cancellation_document: "cancellation_document",
        };

        server
            .mockEndpoint()
            .post("/policies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.policies.issuePolicy({
            quote_request_id: 123,
            quote_reference_id: "550e8400-e29b-41d4-a716-446655440000",
            quote_price_id: "550e8400-e29b-41d4-a716-446655440001",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("issuePolicy (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new YasminaaiApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            quote_request_id: 1,
            quote_reference_id: "quote_reference_id",
            quote_price_id: "quote_price_id",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/policies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.policies.issuePolicy({
                quote_request_id: 1,
                quote_reference_id: "quote_reference_id",
                quote_price_id: "quote_price_id",
            });
        }).rejects.toThrow(YasminaaiApi.UnauthorizedError);
    });

    test("issuePolicy (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new YasminaaiApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            quote_request_id: 1,
            quote_reference_id: "quote_reference_id",
            quote_price_id: "quote_price_id",
        };
        const rawResponseBody = { string: { key: "value" } };

        server
            .mockEndpoint()
            .post("/policies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.policies.issuePolicy({
                quote_request_id: 1,
                quote_reference_id: "quote_reference_id",
                quote_price_id: "quote_price_id",
            });
        }).rejects.toThrow(YasminaaiApi.UnprocessableEntityError);
    });
});
