// This file was auto-generated by Fern from our API Definition.

import * as YasminaaiApi from "../../src/api/index";
import { YasminaaiApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PoliciesClient", () => {
    test("showPolicy", async () => {
        const server = mockServerPool.createServer();
        const client = new YasminaaiApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: 1,
            meta_data: { key: "value" },
            start_date: "start_date",
            provider_policy_id: 1,
            provider_policy: "provider_policy",
            order_status: 1,
            approval_status: 1,
            end_date: "end_date",
            is_claimed: true,
            created_at: "created_at",
            uploaded_at: "2024-01-15T09:30:00Z",
            updated_at: "updated_at",
            client_id: "client_id",
            canceled_at: "canceled_at",
            invoice: "invoice",
            cancellation_document: "cancellation_document",
        };

        server.mockEndpoint().get("/policies/1").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.policies.showPolicy({
            carPolicy: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listPolicies (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new YasminaaiApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            current_page: 1,
            data: [
                {
                    id: 1,
                    meta_data: { key: "value" },
                    start_date: "start_date",
                    provider_policy_id: 1,
                    provider_policy: "provider_policy",
                    order_status: 1,
                    approval_status: 1,
                    end_date: "end_date",
                    is_claimed: true,
                    created_at: "created_at",
                    uploaded_at: "2024-01-15T09:30:00Z",
                    updated_at: "updated_at",
                    client_id: "client_id",
                    canceled_at: "canceled_at",
                    invoice: "invoice",
                    cancellation_document: "cancellation_document",
                },
            ],
            first_page_url: "first_page_url",
            from: 1,
            last_page: 1,
            last_page_url: "last_page_url",
            links: [{ url: "url", label: "label", active: true }],
            next_page_url: "next_page_url",
            path: "path",
            per_page: 1,
            prev_page_url: "prev_page_url",
            to: 1,
            total: 1,
            aggregates: {
                total_count: 12,
                total_price: 42850.75,
                by_month: { "2026-06": { count: 12, total_price: 42850.75 } },
            },
        };

        server.mockEndpoint().get("/policies").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.policies.listPolicies({
            date_from: "2026-06-01",
            date_to: "2026-06-30",
            include_aggregates: true,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listPolicies (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new YasminaaiApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/policies").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.policies.listPolicies();
        }).rejects.toThrow(YasminaaiApi.UnauthorizedError);
    });

    test("issuePolicy (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new YasminaaiApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            otp: "123456",
            quote_request_id: 123,
            quote_reference_id: "550e8400-e29b-41d4-a716-446655440000",
            quote_price_id: "550e8400-e29b-41d4-a716-446655440001",
        };
        const rawResponseBody = {
            id: 1,
            meta_data: { key: "value" },
            start_date: "start_date",
            provider_policy_id: 1,
            provider_policy: "provider_policy",
            order_status: 1,
            approval_status: 1,
            end_date: "end_date",
            is_claimed: true,
            created_at: "created_at",
            uploaded_at: "2024-01-15T09:30:00Z",
            updated_at: "updated_at",
            client_id: "client_id",
            canceled_at: "canceled_at",
            invoice: "invoice",
            cancellation_document: "cancellation_document",
        };

        server
            .mockEndpoint()
            .post("/policies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.policies.issuePolicy({
            otp: "123456",
            quote_request_id: 123,
            quote_reference_id: "550e8400-e29b-41d4-a716-446655440000",
            quote_price_id: "550e8400-e29b-41d4-a716-446655440001",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("issuePolicy (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new YasminaaiApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            otp: "otp",
            quote_request_id: 1,
            quote_reference_id: "quote_reference_id",
            quote_price_id: "quote_price_id",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/policies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.policies.issuePolicy({
                otp: "otp",
                quote_request_id: 1,
                quote_reference_id: "quote_reference_id",
                quote_price_id: "quote_price_id",
            });
        }).rejects.toThrow(YasminaaiApi.UnauthorizedError);
    });

    test("issuePolicy (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new YasminaaiApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            otp: "otp",
            quote_request_id: 1,
            quote_reference_id: "quote_reference_id",
            quote_price_id: "quote_price_id",
        };
        const rawResponseBody = { string: { key: "value" } };

        server
            .mockEndpoint()
            .post("/policies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.policies.issuePolicy({
                otp: "otp",
                quote_request_id: 1,
                quote_reference_id: "quote_reference_id",
                quote_price_id: "quote_price_id",
            });
        }).rejects.toThrow(YasminaaiApi.UnprocessableEntityError);
    });
});
