// This file was auto-generated by Fern from our API Definition.

export const YasminaaiApiEnvironment = {
    Sandbox: "https://sandbox.yasmina.ai/api/v1/car-comp",
    Production: "https://production.yasmina.ai/api/v1/car-comp",
} as const;

export type YasminaaiApiEnvironment =
    | typeof YasminaaiApiEnvironment.Sandbox
    | typeof YasminaaiApiEnvironment.Production;
