// This file was auto-generated by Fern from our API Definition.

export const YasminaaiApiEnvironment = {
    Default: "https://staging.yasmina.ai/api/v1/car-comp",
} as const;

export type YasminaaiApiEnvironment = typeof YasminaaiApiEnvironment.Default;
